name: face_anim
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - aiohappyeyeballs
  - aiohttp
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow-cpp
  - async-lru
  - async-timeout
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - babel
  - backcall
  - beautifulsoup4
  - blas
  - bleach
  - boost-cpp
  - bottleneck
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - charset-normalizer
  - cyrus-sasl
  - cxx-compiler
  - debugpy
  - decorator
  - defusedxml
  - dill
  - exceptiongroup
  - filelock
  - freetype
  - gettext
  - gflags
  - glib
  - glib-tools
  - glog
  - gcc_linux-64
  - gmp
  - gmpy2
  - gst-plugins-base
  - gstreamer
  - h11
  - httpcore
  - httpx
  - huggingface_hub
  - icu
  - idna
  - importlib_metadata
  - importlib_resources
  - intel-openmp
  - ipykernel
  - jedi
  - jinja2
  - jpeg
  - json5
  - jsonschema
  - jsonschema-specifications
  - jupyter
  - jupyter-lsp
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - krb5
  - lcms2
  - lerc
  - libabseil
  - libboost
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libclang13
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libevent
  - libffi
  - libglib
  - libgrpc
  - libiconv
  - libjpeg-turbo
  - libllvm14
  - libnghttp2
  - libpng
  - libpq
  - libprotobuf
  - libsodium
  - libssh2
  - libthrift
  - libtiff
  - libwebp-base
  - libxml2
  - llvm-openmp
  - lz4-c
  - markupsafe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpc
  - mpfr
  - mpmath
  - mysql
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - networkx
  - notebook
  - notebook-shim
  - numexpr
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - orc
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - pcre2
  - pickleshare
  - pillow
  - pip
  - pkgutil-resolve-name
  - ply
  - prometheus_client
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pyqt
  - pyqt5-sip
  - pysocks
  - python==3.9.0
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - python-xxhash
  - pytorch
  - pytz
  - pyyaml
  - pyzmq
  - qt-main
  - qtconsole
  - qtpy
  - re2
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - send2trash
  - setuptools
  - sip
  - six
  - snappy
  - sniffio
  - sqlite
  - stack_data
  - sympy
  - terminado
  - tinycss2
  - tk
  - tokenizers
  - tomli
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - urllib3
  - utf8proc
  - webencodings
  - websocket-client
  - wheel
  - xz
  - yaml
  - zeromq
  - zlib
  - zstd
  - pip:
      - aiosignal
      - appnope
      - asttokens
      - audioread
      - cffi
      - comm
      - contourpy
      - customtkinter
      - cycler
      - cython
      - darkdetect
      - datasets
      - executing
      - face-alignment
      - ffmpeg
      - fonttools
      - frozenlist
      - fsspec
      - gdown
      - huggingface-hub
      - imageio
      - importlib-metadata
      - importlib-resources
      - ipython
      - ipywidgets
      - joblib
      - jupyterlab-widgets
      - kiwisolver
      - lazy-loader
      - librosa
      - llvmlite
      - matplotlib
      - matplotlib-inline
      - multidict
      - multiprocess
      - mutagen
      - numba
      - opencv-python
      - parso
      - pexpect
      - platformdirs
      - pooch
      - prompt-toolkit
      - protobuf
      - pure-eval
      - pyarrow
      - pycparser
      - pydub
      - pygments
      - pyparsing
      - pysptk==1.0.1
      - pywavelets
      - pyworld==0.3.4
      - regex
      - resampy
      - resemblyzer
      - safetensors
      - scikit-image
      - scikit-learn
      - scipy
      - sentencepiece
      - soundfile
      - soupsieve
      - stack-data
      - tensorboardx
      - threadpoolctl
      - tifffile
      - transformers
      - typing
      - tzdata
      - wcwidth
      - webrtcvad
      - widgetsnbextension
      - xxhash
      - yarl
      - zipp
